import type { ChangeHistoryEntry, ManagerSettingUser, OrgSettingsData } from './types';

// 백엔드 API 연동 전까지 화면 확인용으로 쓰는 더미 데이터
export const MOCK_ORG_SETTINGS: OrgSettingsData = {
   orgName: '부트캠프 코딩학원',
   courseName: 'React 풀스택 부트캠프 2기',
   startDate: '2026-02-23',
   endDate: '2026-02-23',
   attendanceUnitPeriods: [
      { id: 'period-1', startDate: '2025-07-01', endDate: '2025-07-31' },
      { id: 'period-2', startDate: '2025-08-01', endDate: '2025-08-31' },
   ],
   warningCriteria: {
      cautionRate: '85',
      warningRate: '75',
      expulsionRiskRate: '65',
   },
};

export const MOCK_USERS: ManagerSettingUser[] = [
   {
      id: 'user-1',
      name: '김철수',
      email: 'chulsoo@camp.kr',
      role: '훈련생',
      team: '팀 A',
      status: '활성',
   },
   {
      id: 'user-2',
      name: '이영희',
      email: 'younghee@camp.kr',
      role: '훈련생',
      team: '팀 B',
      status: '활성',
   },
   {
      id: 'user-3',
      name: '박민준',
      email: 'minjun@camp.kr',
      role: '훈련생',
      team: '팀 A',
      status: '활성',
   },
   {
      id: 'user-4',
      name: '박강사',
      email: 'instructor@camp.kr',
      role: '강사',
      team: null,
      status: '활성',
   },
   {
      id: 'user-5',
      name: '이매니저',
      email: 'manager@camp.kr',
      role: '매니저',
      team: null,
      status: '활성',
   },
   {
      id: 'user-6',
      name: '최탈퇴',
      email: 'old@camp.kr',
      role: '훈련생',
      team: null,
      status: '삭제됨',
   },
   {
      id: 'user-7',
      name: '정하나',
      email: 'hana@camp.kr',
      role: '훈련생',
      team: '팀 B',
      status: '활성',
   },
   {
      id: 'user-8',
      name: '최강사',
      email: 'instructor2@camp.kr',
      role: '강사',
      team: null,
      status: '활성',
   },
];

export const MOCK_CHANGE_HISTORY: ChangeHistoryEntry[] = [
   {
      id: 'history-1',
      changedBy: '이매니저',
      changedAt: '2025.08.01 14:32',
      itemLabel: '출결 단위기간 기준',
      category: '출결 기준',
      beforeValue: '월 단위',
      afterValue: '훈련 개시일 기준',
      isFlagged: true,
   },
   {
      id: 'history-2',
      changedBy: '이매니저',
      changedAt: '2025.07.28 09:15',
      itemLabel: '제적위험 기준 출석률',
      category: '경고·제적 기준',
      beforeValue: '70%',
      afterValue: '65%',
      isFlagged: true,
   },
   {
      id: 'history-3',
      changedBy: '이매니저',
      changedAt: '2025.07.25 16:44',
      itemLabel: '경고 기준 출석률',
      category: '경고·제적 기준',
      beforeValue: '80%',
      afterValue: '75%',
      isFlagged: true,
   },
   {
      id: 'history-4',
      changedBy: '이매니저',
      changedAt: '2025.07.20 11:02',
      itemLabel: '박민준 역할',
      category: '사용자 권한',
      beforeValue: '훈련생',
      afterValue: '강사',
      isFlagged: true,
   },
   {
      id: 'history-5',
      changedBy: '이매니저',
      changedAt: '2025.07.18 10:30',
      itemLabel: '과정명',
      category: '조직 정보',
      beforeValue: 'React 풀스택 부트캠프 1기',
      afterValue: 'React 풀스택 부트캠프 2기',
      isFlagged: false,
   },
   {
      id: 'history-6',
      changedBy: '이매니저',
      changedAt: '2025.07.10 15:20',
      itemLabel: '주의 기준 출석률',
      category: '경고·제적 기준',
      beforeValue: '90%',
      afterValue: '85%',
      isFlagged: false,
   },
   {
      id: 'history-7',
      changedBy: '이매니저',
      changedAt: '2025.07.05 13:00',
      itemLabel: '단위기간 추가',
      category: '출결 기준',
      beforeValue: '1개',
      afterValue: '2개',
      isFlagged: false,
   },
   {
      id: 'history-8',
      changedBy: '이매니저',
      changedAt: '2025.07.01 09:00',
      itemLabel: '조직명',
      category: '조직 정보',
      beforeValue: '-',
      afterValue: '부트캠프 코딩학원',
      isFlagged: false,
   },
];
