name: "Bug Fix"
description: "버그 수정 이슈 템플릿"
title: "[BUGFIX] "
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: problem
    attributes:
      label: "🐛 발생한 문제"
      value: |
      - 
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: "📍 문제 지점"
      value: |
      - 
    validations:
      required: true